export {default as Loading} from "./Loading";
export {default as Avatar} from "./Avatar";
export {default as Menu} from "./Menu";
export {default as Error} from "./Error";
export {default as FieldsForm} from "./FieldsForm";
export {default as CardImage} from "./ImageCard";
export {default as Notification} from "./Notification";
export {default as ModalImage} from "./ImageViewModal";
export {default as CardInfo} from "./InfoCard";
export {default as Forms} from "./Form";
export {default as Search} from "./Search";
export {default as CardList} from "./CardList";
export {default as ButtonAdd} from "./AddButton";
export {default as ButtonEdit} from "./EditButton";
export {default as ModalViewVideo} from "./ModalViewVideo";
export {default as DownLoadButton} from './DownLoadButton';
export {default as NextButton} from './NextButton';
export {default as Print} from './Print';
export {default as ImageButton} from './ImageButton';
export {default as DinamicSelect} from './DinamicSelect';
export {default as ButtonLocationMap} from './ButtonLocationMap';
export {default as DeleteButton} from './DeleteButton';
export {default as CheckboxGroupDinamic} from './CheckboxGroupDinamic';
export {default as TabsEditable} from './TabsEditable';
export { default as Pagination } from "./Pagination";

